/-
F1 square — **the source-coherence laws of the scale field** (`AtlasSourceLaws.lean`, target-free).

The field `U_x(f,t) = x^{-1/2}·f(x/max(t,a))` is GENERATED by `V(f,t) = f(1/max(t,a))`; the laws that a
source-coherent carrier must encode, all proved pointwise from the definitions (band clamp inert on `[0,S]`,
Haar clamp inert on `t ≥ a`, the certified two-sided root):

 * THE ORBIT LAW (`dilRef_orbit`, `Uc_orbit`): if `x'·t = x·t'` (same point of the multiplicative orbit)
   then `x^{-1/2}·U_{x'}(f,t') = x'^{-1/2}·U_x(f,t)`; specialized to `(x,t) ↦ (λx, λt)` in `Uc_orbit_scale`.
   The weight law is exact in squared form: `(invSq(λx))²·λ = (invSq x)²` (`invSq_scale_sq`), i.e. the
   ratio `invSq(λx)/invSq(x)` IS `λ^{-1/2}` — no real square root of `λ` is introduced.
 * THE SOURCE-COHERENCE LAW (`Uc_eq_invSq_Vc_shift`): for `1 ≤ x ≤ S` and `t ≥ a·x`,
   `U_x(f,t) = x^{-1/2}·V(f, t/x)`.
 * THE SUPPORT-FORCED ZERO ROWS (`Uc_zero_row`, `Uc_zero_row_upR`): at a rational scale `1 ≤ q ≤ S` and
   `t ≤ a·q`, `U_q(f,t) = 0` for core tests; in particular every prime row with `a + w ≤ n·a` vanishes on
   the whole window.

HONEST SCOPE: these identify VALUES of the one field along orbits and identify `U` as a shift of `V`.
They do not couple the atomic prime measure `2Λ(n)dν` to the continuous pole/tail/far densities in `x`;
no contraction, positivity, or dominance is claimed or implied.
Pure Lean 4 core, no Mathlib, no `sorry`/`native_decide`, choice-free.
-/

import F1Square.Square.AtlasPrimeFold

namespace UOR.Bridge.F1Square.Square

open UOR.Bridge.F1Square.Analysis

theorem dilRef_f (C : NormCtx) (x : Real) (f : L2Test) (t : Real) :
    (dilRef C x f).f t = f.f (Rmul (xBand C x) (clampedInv C.a C.han C.had t)) := rfl

/-- The band clamp is inert on `[0, S]`. -/
theorem xBand_inert (C : NormCtx) {x : Real} (h0 : Rle zero x) (hS : Rle x (ofQ C.S C.hSd)) : Req (xBand C x) x :=
  qBandQ_eq_of_band h0 hS

theorem Rnonneg_of_ge_a (C : NormCtx) {t : Real} (ht : Rle (ofQ C.a C.had) t) : Rnonneg t :=
  Rnonneg_of_Rle_zero (Rle_trans (Rle_ofQ_ofQ (by decide) C.had (by
    show (0 : Int) * (C.a.den : Int) ≤ C.a.num * ((1 : Nat) : Int)
    have := C.han; push_cast; omega)) ht)

/-- `(x·t⁻¹)·(t·t') ≈ x·t'`. -/
theorem inv_cross_alg (x t t' : Real) {kt : Nat} (hkt : Qlt (Qbound kt) (t.seq kt)) :
    Req (Rmul (Rmul x (Rinv t kt hkt)) (Rmul t t')) (Rmul x t') := by
  refine Req_trans (Rmul_assoc _ _ _) (Rmul_congr (Req_refl x) ?_)
  refine Req_trans (Req_symm (Rmul_assoc _ _ _)) ?_
  refine Req_trans (Rmul_congr (Req_trans (Rmul_comm _ _) (Rmul_Rinv_self hkt)) (Req_refl _)) ?_
  exact Rone_mul _

-- ===========================================================================
-- (1) THE ORBIT LAW.
-- ===========================================================================

/-- **The orbit law for the raw dilation**: `x'·t = x·t'` ⟹ `f(x/t) = f(x'/t')` (band and Haar clamps inert). -/
theorem dilRef_orbit (C : NormCtx) (f : L2Test) {x x' t t' : Real}
    (h0 : Rle zero x) (hS : Rle x (ofQ C.S C.hSd)) (h0' : Rle zero x') (hS' : Rle x' (ofQ C.S C.hSd))
    (ht : Rle (ofQ C.a C.had) t) (ht' : Rle (ofQ C.a C.had) t') (horb : Req (Rmul x' t) (Rmul x t')) :
    Req ((dilRef C x f).f t) ((dilRef C x' f).f t') := by
  obtain ⟨kt, hkt⟩ := Pos_of_Rle_ofQ C.han C.had ht
  obtain ⟨kt', hkt'⟩ := Pos_of_Rle_ofQ C.han C.had ht'
  have e1 : Req (Rmul (xBand C x) (clampedInv C.a C.han C.had t)) (Rmul x (Rinv t kt hkt)) :=
    Rmul_congr (xBand_inert C h0 hS) (clampedInv_eq_of_ge hkt ht)
  have e2 : Req (Rmul (xBand C x') (clampedInv C.a C.han C.had t')) (Rmul x' (Rinv t' kt' hkt')) :=
    Rmul_congr (xBand_inert C h0' hS') (clampedInv_eq_of_ge hkt' ht')
  have hprod : Rle (ofQ (mul C.a C.a) (Qmul_den_pos C.had C.had)) (Rmul t t') :=
    Rle_trans (Rle_of_Req (Req_symm (Rmul_ofQ_ofQ C.had C.had)))
      (Rmul_le_Rmul_both (Rnonneg_ofQ C.had (Int.le_of_lt C.han)) (Rnonneg_of_ge_a C ht') ht ht')
  obtain ⟨kp, hkp⟩ := Pos_of_Rle_ofQ (Int.mul_pos C.han C.han) (Qmul_den_pos C.had C.had) hprod
  have key : Req (Rmul x (Rinv t kt hkt)) (Rmul x' (Rinv t' kt' hkt')) := by
    refine Rmul_right_cancel hkp ?_
    refine Req_trans (inv_cross_alg x t t' hkt) ?_
    refine Req_trans (Req_symm horb) ?_
    refine Req_symm (Req_trans (Rmul_congr (Req_refl _) (Rmul_comm t t')) ?_)
    exact inv_cross_alg x' t' t hkt'
  rw [dilRef_f, dilRef_f]
  exact f.hfc _ _ (Req_trans e1 (Req_trans key (Req_symm e2)))

/-- **★ THE ORBIT LAW OF THE FIELD**: `x'·t = x·t'` ⟹ `x'^{-1/2}·U_x(f,t) = x^{-1/2}·U_{x'}(f,t')`. -/
theorem Uc_orbit (C : NormCtx) (f : L2Test) {x x' t t' : Real}
    (h0 : Rle zero x) (hS : Rle x (ofQ C.S C.hSd)) (h0' : Rle zero x') (hS' : Rle x' (ofQ C.S C.hSd))
    (ht : Rle (ofQ C.a C.had) t) (ht' : Rle (ofQ C.a C.had) t') (horb : Req (Rmul x' t) (Rmul x t')) :
    Req (Rmul (invSq C x') (Uc C x f t)) (Rmul (invSq C x) (Uc C x' f t')) := by
  unfold Uc
  refine Req_trans (Rmul_congr (Req_refl _) (Rmul_congr (Req_refl _) (dilRef_orbit C f h0 hS h0' hS' ht ht' horb))) ?_
  exact swap_w_ac _ _ _

/-- **The multiplicative-orbit law** `(x,t) ↦ (λx, λt)`: `invSq(λx)·U_x(f,t) = invSq(x)·U_{λx}(f,λt)`. -/
theorem Uc_orbit_scale (C : NormCtx) (f : L2Test) {x t l : Real}
    (h0 : Rle zero x) (hS : Rle x (ofQ C.S C.hSd)) (h0' : Rle zero (Rmul l x)) (hS' : Rle (Rmul l x) (ofQ C.S C.hSd))
    (ht : Rle (ofQ C.a C.had) t) (ht' : Rle (ofQ C.a C.had) (Rmul l t)) :
    Req (Rmul (invSq C (Rmul l x)) (Uc C x f t)) (Rmul (invSq C x) (Uc C (Rmul l x) f (Rmul l t))) :=
  Uc_orbit C f h0 hS h0' hS' ht ht' (Req_trans (Rmul_congr (Rmul_comm l x) (Req_refl t)) (Rmul_assoc x l t))

-- ===========================================================================
-- (2) THE WEIGHT LAW IN SQUARED FORM.
-- ===========================================================================

/-- On the band `c ≤ x ≤ B`: `(x^{-1/2})²·x = 1` for the certified two-sided root. -/
theorem invSq_sq_mul_self (C : NormCtx) {x : Real} (hc : Rle (ofQ (canonC C) (canonC_den C)) x)
    (hB : Rle x (ofQ (canonB C) (canonB_den C))) {kx : Nat} (hkx : Qlt (Qbound kx) (x.seq kx)) :
    Req (Rmul (Rmul (invSq C x) (invSq C x)) x) one := by
  have hsq := invSqrtTwoF_sq (canonC C) (canonB C) (canonC_num C) (canonC_den C) (canonB_den C) (canonB_one C)
    (canonC_le_B C) (C.X + 1) (Nat.succ_pos C.X) (canonB_le_N C) x
  have hrad : Req (twoRad (canonC C) (canonB C) (canonC_num C) (canonC_den C) (canonB_den C) x) (Rinv x kx hkx) := by
    unfold twoRad twoBand
    exact Req_trans (clampedInv_congr _ _ _ (qBandQ_eq_of_band hc hB)) (clampedInv_eq_of_ge hkx hc)
  refine Req_trans (Rmul_congr (Req_trans hsq hrad) (Req_refl x)) ?_
  exact Req_trans (Rmul_comm _ _) (Rmul_Rinv_self hkx)

/-- **★ THE WEIGHT LAW**: `x, λx ∈ [c,B]` ⟹ `(invSq(λx))²·λ = (invSq x)²` — the ratio `invSq(λx)/invSq(x)`
    is `λ^{-1/2}` exactly, in squared form. -/
theorem invSq_scale_sq (C : NormCtx) {x l : Real} (hc : Rle (ofQ (canonC C) (canonC_den C)) x)
    (hB : Rle x (ofQ (canonB C) (canonB_den C))) (hc' : Rle (ofQ (canonC C) (canonC_den C)) (Rmul l x))
    (hB' : Rle (Rmul l x) (ofQ (canonB C) (canonB_den C))) :
    Req (Rmul (Rmul (invSq C (Rmul l x)) (invSq C (Rmul l x))) l) (Rmul (invSq C x) (invSq C x)) := by
  obtain ⟨kx, hkx⟩ := Pos_of_Rle_ofQ (canonC_num C) (canonC_den C) hc
  obtain ⟨kl, hkl⟩ := Pos_of_Rle_ofQ (canonC_num C) (canonC_den C) hc'
  refine Rmul_right_cancel hkx ?_
  refine Req_trans (Rmul_assoc _ _ _) ?_
  exact Req_trans (invSq_sq_mul_self C hc' hB' hkl) (Req_symm (invSq_sq_mul_self C hc hB hkx))

-- ===========================================================================
-- (3) THE SOURCE-COHERENCE LAW `U_x(f,t) = x^{-1/2}·V(f, t/x)` on `t ≥ a·x`.
-- ===========================================================================

theorem Rle_a_of_ax (C : NormCtx) {x t : Real} (hx1 : Rle one x) (hax : Rle (Rmul (ofQ C.a C.had) x) t) :
    Rle (ofQ C.a C.had) t :=
  Rle_trans (Rle_of_Req (Req_symm (Rmul_one _)))
    (Rle_trans (Rmul_le_Rmul_left (Rnonneg_ofQ C.had (Int.le_of_lt C.han)) hx1) hax)

/-- **★ `U` IS A SHIFT OF `V`**: for `1 ≤ x ≤ S` and `t ≥ a·x`, `U_x(f,t) = x^{-1/2}·V(f, t·x⁻¹)`. -/
theorem Uc_eq_invSq_Vc_shift (C : NormCtx) (f : L2Test) {x t : Real} (hx1 : Rle one x) (hS : Rle x (ofQ C.S C.hSd))
    {kx : Nat} (hkx : Qlt (Qbound kx) (x.seq kx)) (hax : Rle (Rmul (ofQ C.a C.had) x) t) :
    Req (Uc C x f t) (Rmul (invSq C x) (Vc C f (Rmul t (Rinv x kx hkx)))) := by
  have h0 : Rle zero x := Rle_trans (Rle_ofQ_ofQ (by decide) (by decide) (by decide)) hx1
  have ht : Rle (ofQ C.a C.had) t := Rle_a_of_ax C hx1 hax
  have ht' : Rle (ofQ C.a C.had) (Rmul t (Rinv x kx hkx)) := by
    refine Rle_trans (Rle_of_Req ?_) (Rmul_le_Rmul_right (Rnonneg_Rinv x kx hkx) hax)
    exact Req_symm (Req_trans (Rmul_assoc _ _ _) (Req_trans (Rmul_congr (Req_refl _) (Rmul_Rinv_self hkx)) (Rmul_one _)))
  have horb : Req (Rmul one t) (Rmul x (Rmul t (Rinv x kx hkx))) := by
    refine Req_trans (Rone_mul t) (Req_symm ?_)
    refine Req_trans (Rmul_congr (Req_refl x) (Rmul_comm _ _)) ?_
    exact Req_trans (Req_symm (Rmul_assoc _ _ _)) (Req_trans (Rmul_congr (Rmul_Rinv_self hkx) (Req_refl t)) (Rone_mul t))
  unfold Uc
  refine Rmul_congr (Req_refl _) ?_
  refine Req_trans (dilRef_orbit C f h0 hS (Rle_ofQ_ofQ (by decide) (by decide) (by decide))
    (Rle_ofQ_ofQ (by decide) C.hSd C.hS1) ht ht' horb) ?_
  rw [dilRef_f]
  show Req (f.f (Rmul (xBand C one) (clampedInv C.a C.han C.had (Rmul t (Rinv x kx hkx)))))
           (f.f (clampedInv C.a C.han C.had (Rmul t (Rinv x kx hkx))))
  exact f.hfc _ _ (Req_trans (Rmul_congr (xBand_one C) (Req_refl _)) (Rone_mul _))

-- ===========================================================================
-- (4) THE SUPPORT-FORCED ZERO ROWS.
-- ===========================================================================

/-- `q·(1/(a·q)) = 1/a` as rationals (`a, q > 0`). -/
theorem q_mul_inv_aq (a q : Q) (han : 0 < a.num) (hqn : 0 < q.num) :
    Qeq (mul q (Qinv (mul a q))) (Qinv a) := by
  simp only [Qeq, mul, Qinv]
  push_cast [Int.toNat_of_nonneg (Int.le_of_lt han), Int.toNat_of_nonneg (Int.le_of_lt (Int.mul_pos han hqn))]
  ring_uor

/-- **★ THE ZERO ROWS**: at a rational scale `1 ≤ q ≤ S` and `t ≤ a·q`, `U_q(f,t) = 0` for a core test
    (the dilated argument `q/max(t,a) ≥ 1/a` lies beyond the support). -/
theorem Uc_zero_row (C : NormCtx) (f : L2Test) (hf : CoreTest C.geom f) (q : Q) (hqd : 0 < q.den)
    (hq1 : Qle (⟨1, 1⟩ : Q) q) (hqS : Qle q C.S) {t : Real}
    (ht : Rle t (ofQ (mul C.a q) (Qmul_den_pos C.had hqd))) :
    Req (Uc C (ofQ q hqd) f t) zero := by
  have hqn : 0 < q.num := qnum_pos_of_one_le hqd hq1
  have haq : Qle C.a (mul C.a q) := by
    have h := hq1
    simp only [Qle, mul] at h ⊢
    push_cast at h ⊢
    have e : C.a.num * ((C.a.den : Int) * (q.den : Int)) = C.a.num * (C.a.den : Int) * (q.den : Int) := by ring_uor
    have e2 : C.a.num * q.num * (C.a.den : Int) = C.a.num * (C.a.den : Int) * q.num := by ring_uor
    have hpos : 0 ≤ C.a.num * (C.a.den : Int) := Int.mul_nonneg (Int.le_of_lt C.han) (Int.ofNat_nonneg _)
    rw [e, e2]
    exact Int.mul_le_mul_of_nonneg_left (by omega) hpos
  have hq0 : Qle (⟨0, 1⟩ : Q) q := Qle_trans (by decide) (by decide) hq1
  have hcinv : Rle (ofQ (Qinv (mul C.a q)) (Qinv_den_pos (Int.mul_pos C.han hqn))) (clampedInv C.a C.han C.had t) :=
    ofQ_inv_le_clampedInv C.han C.had (Qmul_den_pos C.had hqd) (Int.mul_pos C.han hqn) ht haq
  have hband : Req (xBand C (ofQ q hqd)) (ofQ q hqd) :=
    xBand_inert C (Rle_ofQ_ofQ (by decide) hqd hq0) (Rle_ofQ_ofQ hqd C.hSd hqS)
  have hprod : Req (Rmul (ofQ q hqd) (ofQ (Qinv (mul C.a q)) (Qinv_den_pos (Int.mul_pos C.han hqn))))
      (ofQ (Qinv C.a) (Qinv_den_pos C.han)) :=
    Req_trans (Rmul_ofQ_ofQ hqd (Qinv_den_pos (Int.mul_pos C.han hqn)))
      (ofQ_congr (Qmul_den_pos hqd (Qinv_den_pos (Int.mul_pos C.han hqn))) (Qinv_den_pos C.han) (q_mul_inv_aq C.a q C.han hqn))
  have harg : Rle (ofQ (Qinv C.a) (Qinv_den_pos C.han)) (Rmul (xBand C (ofQ q hqd)) (clampedInv C.a C.han C.had t)) := by
    refine Rle_trans (Rle_of_Req (Req_symm hprod)) ?_
    exact Rmul_le_Rmul_both (Rnonneg_ofQ hqd (Int.le_of_lt hqn)) (Rnonneg_clampedInv C.a C.han C.had t)
      (Rle_of_Req (Req_symm hband)) hcinv
  unfold Uc
  rw [dilRef_f]
  exact Req_trans (Rmul_congr (Req_refl _) (hf.hgh _ harg)) (Rmul_zero _)

/-- **The prime rows with `a + w ≤ n·a` vanish on the whole window**: `U_n(f,t) = 0` for `t ≤ a + w`. -/
theorem Uc_zero_row_upR (C : NormCtx) (f : L2Test) (hf : CoreTest C.geom f) (m : Nat) (hm : m < C.X)
    (hrow : Qle (add C.a C.w) (mul C.a (⟨((m + 1 : Nat) : Int), 1⟩ : Q))) {t : Real}
    (ht : Rle t (ofQ (add C.a C.w) (add_den_pos C.had C.hw))) :
    Req (Uc C (upR m) f t) zero :=
  Uc_zero_row C f hf (⟨((m + 1 : Nat) : Int), 1⟩ : Q) Nat.one_pos
    (by show (1 : Int) * ((1 : Nat) : Int) ≤ ((m + 1 : Nat) : Int) * ((1 : Nat) : Int); push_cast; omega)
    (placeData_in_band C m hm 0).2.2
    (Rle_trans ht (Rle_ofQ_ofQ _ _ hrow))

end UOR.Bridge.F1Square.Square
